// <auto-generated />
namespace Questionnaire.DomainModel.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class AddEntityState : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddEntityState));
        
        string IMigrationMetadata.Id
        {
            get { return "201612200555365_Add-EntityState"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
